### ISSUE TITLE
[BUG] import.meta.resolve in mocked import never returns

### ISSUE THREAD

**Issue by lukekarrys** [tapjs/tapjs#1042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

Calling `import.meta.resolve()` from inside a module that is loaded with `t.mockImport` will never return.

### Reproduction

Repro gist: https://gist.github.com/lukekarrys/8ab4ab047b363d98ed825eb560a02c9b

The gist of the gist is that a function like the following which calls `import.meta.resolve` will never return when called after being loaded with `t.mockImport`. In the `index.js` file, the `console.error(resolved)` will never get called, and thus the test will never finish.

**index.js**
```js
export const index = () => {
  console.error('start index')
  const resolved = import.meta.resolve('abbrev')
  console.error(resolved)
}
```

**test.js**
```js
import t from 'tap'

t.test('test', async t => {
  const { index } = await t.mockImport('./index.js')
  console.error('mock import')
  index()
  console.error('call import')
  t.ok(true)
})
```

### Environment

```sh
# npm ls tap
tap-import-meta-resolve@1.0.0 /Users/lukekarrys/Desktop/scratch/tap-import-meta-resolve
└── tap@21.0.1
# npx tap versions
tap: 21.0.1
"@tapjs/config": 5.0.0
"@tapjs/core": 4.0.0
"@tapjs/run": 4.0.1
"@tapjs/stack": 4.0.0
"@tapjs/test": 4.0.0
tap-parser: 18.0.0
tap-yaml: 4.0.0
tcompare: 9.0.0
plugins:
  "@tapjs/after": 3.0.0
  "@tapjs/after-each": 4.0.0
  "@tapjs/asserts": 4.0.0
  "@tapjs/before": 4.0.0
  "@tapjs/before-each": 4.0.0
  "@tapjs/chdir": 3.0.0
  "@tapjs/filter": 4.0.0
  "@tapjs/fixture": 4.0.0
  "@tapjs/intercept": 4.0.0
  "@tapjs/mock": 4.0.0
  "@tapjs/node-serialize": 4.0.0
  "@tapjs/snapshot": 4.0.0
  "@tapjs/spawn": 4.0.0
  "@tapjs/stdin": 4.0.0
  "@tapjs/typescript": 3.0.0
  "@tapjs/worker": 4.0.0
# npx tap config list
# vim: set filetype=yaml :
browser: true
color: true
coverage-report:
  - text
exclude:
  - "**/@(fixture*(s)|dist)/**"
include:
  - "**/@(test?(s)|__test?(s)__)/**/*.@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/*.@(test?(s)|spec).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/test?(s).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
jobs: 9
reporter: base
snapshot-clean-cwd: true
timeout: 30
# npx tap plugin list
@tapjs/after
@tapjs/after-each
@tapjs/asserts
@tapjs/before
@tapjs/before-each
@tapjs/chdir
@tapjs/filter
@tapjs/fixture
@tapjs/intercept
@tapjs/mock
@tapjs/node-serialize
@tapjs/snapshot
@tapjs/spawn
@tapjs/stdin
@tapjs/typescript
@tapjs/worker
# posix:
Darwin pieholden.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:25 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6030 arm64 arm Darwin
```

**Comment by isaacs** [comment]
Yes, this is a deadlock introduced by node doing import resolution in a separate thread. The mocked import needs to talk to the main thread (where you've defined the mocking) to figure out how to resolve things, but that main thread is halted in order to do the resolution.

There is no way that tap, or any other import-mocking library, can possibly work around this, I'm afraid.
