### ISSUE TITLE
1.0 milestone tracker

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#124]
- [X] writable parser class
- [x] test class (in progress)
  - [X] test class basics
  - [X] error handling
    - [x] More error handling tests.
  - [X] root test object (ie, the `require('tap')`)
  - [x] fancy asserts (repurpose most of `tap-assert.js`)
    - [x] Use `at` field in diags to display location (like Code)
    - [x] Use `Error.captureStackTrace`
  - [x] add Test.prototype.spawn()
    - Question: should `t.spawn('foo.js')` just go ahead and assume it's node?  or do we want to require the user to do `t.spawn(process.execPath, [ path.resolve(__dirname, 'foo.js') ])`?  Second is definitely simpler, but less cute.
- [x] human-friendly runner (Prereq: `t.spawn()`)
- [x] review legacy tests (port to run on new code explicitly)
- [x] strip out legacy code
- [x] Docs
  - [x] Document Consumer and Test classes
  - [x] Example red-X/green-check reporter
  - [x] Example using http://npm.im/code assertion library
- [ ] Coverage?  Somehow?

**Comment by isaacs** [comment]
So, as of 3b858929d6ac548b031ca4f74e6f390b147f234f, the Test class is pretty well where I want it, and very well covered by test cases.

The lack of a human-friendly runner is really starting to get unpleasant though.  That has to be the next thing, now that `t.spawn()` works.

**Comment by othiym23** [comment]
I would love it if you either removed coverage entirely or looked at something like http://npm.im/argg, and provide a generic hook that another coverage framework could tap into, so to speak. I'm trying to figure out how to mash up babeljs source maps and istanbul with tap right now, and having some kind of generic way of doing this that doesn't predetermine the coverage framework used would be super handy.

**Comment by othiym23** [comment]
Also I would be _simply delighted_ to help you write expanded docs for v1, because then I would have docs, and I want them very much.

**Comment by isaacs** [comment]
Done and published.  Coverage will come soon-ish, via another tool that handles child process spawning.
