### ISSUE TITLE
Todo list for tap v15

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#603]
## node-tap changes
- [x] breaking: Remove `--esm` (#651)
- [x] breaking: Upgrade to nyc 15 (#650, tapjs/libtap#9)
- [x] breaking: default `ts: false` and `jsx: false` (#651)
- [x] breaking: default `check-coverage: true` (everyone joins the `--100` club!)
- [x] refactor: Split this lib into two modules: `libtap` (all the library bits that tests actually use) and `tap` (the runner, watcher, reporter, repl, nyc logic, etc.)
- [x] remove `source-map-support` from async-hook-domain (unnecessary, and the wrong place for this)
- [x] make the stack-utils API nicer
- [x] breaking: Drop support for node <= 8
- [x] breaking: change snapshot file extensions to `.cjs`
- [x] breaking: deprecate aliases (#649)
- [x] breaking: add conditional exports to support named ESM exports, forbid outside resolve of internal-only `tap` sources from other modules

## libtap changes
- [x] breaking: Separate `t.has` from `t.match`.  In general, make all `tcompare` methods map directly to a test assertion of the same name.
- [x] breaking: Upgrade to tcompare 4.x, DRY all diffing logic into that one location.  (No need to handle strings separately, etc.)
- [x] add inheritable `t.compareOptions` object to pass options to tcompare
- [x] refactor: Split `lib/test.js` into parts.  It's way too long.
- [x] put `t.testdir()` fixtures in a folder that is excluded by the default `test-regex` conf.  (Like, `./fixtures/${test name}` or something.)
- [x] breaking: add conditional exports to support named ESM exports, forbid outside resolve of internal-only `libtap` sources from other modules (tapjs/libtap#10)

**Comment by coreyfarrell** [comment]
Please let me know when you start work on `libtap`, I'd like to participate / influence the scope of that.

**Comment by jsumners** [comment]
Please default `ts: false` and `jsx: false` as well.

**Comment by isaacs** [comment]
@jsumners I'm fine with that, adding to the OP.

**Comment by jsumners** [comment]
![](https://media.tenor.com/images/85d05888b1b89430da61578ccc72891e/tenor.gif)

**Comment by coreyfarrell** [comment]
@isaacs `t.spawn()` returns a promise which resolves to `t`, IMO this is not very useful.  Any objection to making this resolve true or false?  My own use-case is:
```js
if (!(await t.spawn(...test1Args))) {
  process.exit(1);
}

// run the remaining test files which cannot succeed if test1 failed.
```

Currently I need some trickery to accomplish this:
```js
const test1Promise = t.spawn(...test1Args);
const test1Spawn = t.occupied;
await test1Promise;
if (!test1Spawn.results.ok) {
  process.exit(1);
}
```

I know this would require changing `this.sub`, I haven't untangled the effect of this yet just wanted to get your thoughts before I put work into this.

**Comment by isaacs** [comment]
I'd prefer to not make `t.spawn()` an odd duck here, but I agree that having it resolve to the parent test is a bit odd.

Maybe the right answer is to have child test promises resolve to something more sensible, like the `child.results` object?  Then you could do `if (!(await t.spawn(...test1Args)).ok) { ... }`, but you could also do `if (!(await t.test(name, testFn)).ok) { ... }`.

**Comment by isaacs** [comment]
Another option is just to make the test bail out if the subsequent tests can't succeed when it fails.

```js
// add buffered: false if t.jobs > 1, so that this test is serialized
t.spawn(cmd, [...args], { bail: true, /* buffered: false */ })
t.test('the thing spawned successfully as you know', ...)
```

**Comment by coreyfarrell** [comment]
> I'd prefer to not make `t.spawn()` an odd duck here, but I agree that having it resolve to the parent test is a bit odd.

Aren't `t.spawn()` / `t.sub()` the odd ducks now?  I mean don't most assertions return/resolve to true or false?  You're idea of having `t.sub()` resolve to `child.results` or even just resolving to `child` would be reasonable as well.  Is there a use-case for `t === await t.spawn(cmd)`?

> Another option is just to make the test bail out if the subsequent tests can't succeed when it fails.
> 
> ```js
> // add buffered: false if t.jobs > 1, so that this test is serialized
> t.spawn(cmd, [...args], { bail: true, /* buffered: false */ })
> t.test('the thing spawned successfully as you know', ...)
> ```

This does work for my use case and it actually makes sense for the test output to report 'bailout' in my test.

**Comment by pemrouz** [comment]
Is there any plans to allow `import { test } from 'tap'` too?

**Comment by coreyfarrell** [comment]
@pemrouz Assuming you are talking about node.js native ESM that is dependent on conditional exports.  This feature was just unflagged in node.js 13.7.0 but it still produces an "experimental" warning in addition to the warning produced by use of native ES modules.

**Comment by jsumners** [comment]
@isaacs I think this can be closed now?

**Comment by isaacs** [comment]
Indeed!  Whatever isn't done should be a new issue, now that 15 is shipped to latest.
